//! Receipt-gated recovery for a multi-member caravan missing its native Stack.
//!
//! Ordinary membership remains the only authority that labels and retargets
//! pull requests. This command repairs only the provider representation after
//! those mutations are already exact. Preview seals current repository,
//! membership, head/base, check, rollout and mapping evidence into a plan hash;
//! apply independently rediscovers the same evidence before issuing at most one
//! idempotent Stack create/add request. It never rewrites a source head or changes a
//! PR base, label, comment, or merge state.

use std::collections::{BTreeMap, BTreeSet};
use std::time::{Duration, Instant};

use clap::Args;
use mcp_cli::ErrorCategory;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::command::{CommandRunner, ProcessRunner};
use crate::config::{CaravanConfig, StackType};
use crate::github::{
    GitHubMutationAdapter, GitHubStackCreatePlan, GitHubStackMutationDisposition,
    GitHubStackMutationError, GitHubStackMutationReceipt, GitHubStackTopology, MutationError,
};
use crate::model::{
    BranchSnapshot, Caravan, CheckSnapshot, CheckState, PrNumber, PullRequestPrecondition,
    PullRequestSnapshot, PullRequestState, RepositoryId,
};
use crate::pause::PauseStatus;
use crate::read::{
    NativeStackStatus, StackBackendStatus, StackCapability, StackMutationSupport, StatusOutput,
};
use crate::stack_membership::{
    NativeMembershipCheckpoint, NativeMembershipError, NativeMembershipPlan,
    NativeMembershipReceipt,
};
use crate::{AppContext, AppError};

const MAX_TEXT: usize = 2_000;

/// Read-only recovery planning input.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, Args)]
pub struct NativeStackRecoveryPreviewInput {
    /// Exact root of the already-formed multi-member caravan.
    #[arg(long)]
    pub root: u64,
    /// Audited operator or scheduler identity.
    #[arg(long)]
    pub actor: String,
    /// Bounded reason for repairing the missing provider representation.
    #[arg(long)]
    pub reason: String,
}

/// Mutation input, fenced by the exact hash returned from preview.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema, Args)]
pub struct NativeStackRecoveryApplyInput {
    /// Exact root of the already-formed multi-member caravan.
    #[arg(long)]
    pub root: u64,
    /// Audited operator or scheduler identity; must equal preview.
    #[arg(long)]
    pub actor: String,
    /// Bounded reason; must equal preview.
    #[arg(long)]
    pub reason: String,
    /// Exact immutable plan hash returned by `recovery-preview`.
    #[arg(long)]
    pub plan_hash: String,
}

/// One exact member generation authorized by the recovery plan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct NativeStackRecoveryMember {
    pub position: u32,
    pub pr: PrNumber,
    pub head_ref: String,
    pub expected: PullRequestPrecondition,
    pub draft: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merge_state_status: Option<String>,
    /// Current, identity-deduplicated checks; all are successful.
    pub authoritative_checks: Vec<CheckSnapshot>,
    /// Older check generations retained only as bounded audit evidence.
    #[serde(default)]
    pub superseded_checks: Vec<CheckSnapshot>,
}

/// Immutable no-write authorization produced by preview and regenerated by apply.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct NativeStackRecoveryPlan {
    pub schema_version: u32,
    pub operation_id: String,
    pub repository: RepositoryId,
    pub caravan_id: PrNumber,
    pub members: Vec<NativeStackRecoveryMember>,
    pub desired: GitHubStackTopology,
    /// Exact provider create/add continuation. Legacy zero-mapping recovery
    /// synthesizes Create; a persisted failed append retains Add.
    pub action: NativeMembershipPlan,
    pub actor: String,
    pub reason: String,
    pub config_fingerprint: String,
    /// A formation checkpoint exists when the original join reached ordinary
    /// membership but did not seal native provider convergence.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pending_membership_checkpoint_hash: Option<String>,
    /// The plan permits only zero mappings, or one exact desired mapping on an
    /// idempotent retry after a response was lost. Multiple/drifted mappings are
    /// always refused.
    pub mapping_precondition: String,
    pub plan_hash: String,
}

impl NativeStackRecoveryPlan {
    fn seal(mut self) -> Self {
        self.plan_hash.clear();
        self.plan_hash = self.expected_hash();
        self
    }

    fn expected_hash(&self) -> String {
        let mut material = self.clone();
        material.plan_hash.clear();
        crate::membership::fnv1a64(
            &serde_json::to_vec(&material).expect("native Stack recovery plan serializes"),
        )
    }

    #[must_use]
    pub fn verify(&self) -> bool {
        !self.plan_hash.is_empty() && self.plan_hash == self.expected_hash()
    }
}

/// Current provider-mapping observation kept outside the plan hash so an exact
/// already-created Stack remains an idempotent retry of an absent-mapping plan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum NativeStackRecoveryObservation {
    Absent,
    ExactPrefixPendingAdd,
    ExactAlreadySatisfied,
}

/// Preview/apply receipt. Apply always carries the provider's sealed mutation
/// receipt, including recovered-after-ambiguous and already-satisfied outcomes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct NativeStackRecoveryOutput {
    pub schema_version: u32,
    pub plan: NativeStackRecoveryPlan,
    pub observation: NativeStackRecoveryObservation,
    pub mutated: bool,
    pub source_heads_unchanged: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_receipt: Option<GitHubStackMutationReceipt>,
    pub next: String,
}

struct RecoveryFacts<'a> {
    repository: &'a RepositoryId,
    healthy: bool,
    default_branch: &'a BranchSnapshot,
    caravans: &'a [Caravan],
    pulls: &'a BTreeMap<PrNumber, PullRequestSnapshot>,
    backend: &'a StackBackendStatus,
    pauses: &'a [PauseStatus],
}

impl<'a> RecoveryFacts<'a> {
    fn from_status(status: &'a StatusOutput) -> Self {
        Self {
            repository: &status.repository,
            healthy: status.healthy,
            default_branch: &status.analysis.fleet.default_branch,
            caravans: &status.analysis.fleet.caravans,
            pulls: &status.analysis.pull_requests,
            backend: &status.stack_backend,
            pauses: &status.pauses,
        }
    }
}

trait NativeStackRecoveryProvider {
    fn verify_precondition_with_checks(
        &self,
        repository: &RepositoryId,
        expected: &PullRequestPrecondition,
    ) -> Result<PullRequestSnapshot, MutationError>;

    fn verify_precondition(
        &self,
        repository: &RepositoryId,
        expected: &PullRequestPrecondition,
    ) -> Result<PullRequestSnapshot, MutationError>;

    fn converge_membership(
        &self,
        plan: &NativeMembershipPlan,
    ) -> Result<NativeMembershipReceipt, NativeMembershipError>;
}

impl<R: CommandRunner> NativeStackRecoveryProvider for GitHubMutationAdapter<R> {
    fn verify_precondition_with_checks(
        &self,
        repository: &RepositoryId,
        expected: &PullRequestPrecondition,
    ) -> Result<PullRequestSnapshot, MutationError> {
        self.verify_precondition_with_checks(repository, expected)
    }

    fn verify_precondition(
        &self,
        repository: &RepositoryId,
        expected: &PullRequestPrecondition,
    ) -> Result<PullRequestSnapshot, MutationError> {
        self.verify_precondition(repository, expected)
    }

    fn converge_membership(
        &self,
        plan: &NativeMembershipPlan,
    ) -> Result<NativeMembershipReceipt, NativeMembershipError> {
        self.converge_native_membership(plan)
    }
}

/// Build a no-write exact recovery authorization.
pub fn preview(
    context: &AppContext,
    input: &NativeStackRecoveryPreviewInput,
) -> Result<NativeStackRecoveryOutput, AppError> {
    validate_input(input.root, &input.actor, &input.reason)?;
    let deadline = Instant::now() + Duration::from_secs(context.config.sync.max_duration_secs);
    let status = crate::read::fleet_status(context, deadline, None)?;
    crate::initialization::require_ready(&status.initialization)?;
    let pending =
        crate::stack_membership::load_pending(&context.repository_path, PrNumber(input.root))?;
    let (plan, observation) = build_plan(
        &context.config,
        &RecoveryFacts::from_status(&status),
        PrNumber(input.root),
        &input.actor,
        &input.reason,
        pending.as_ref(),
    )?;
    Ok(NativeStackRecoveryOutput {
        schema_version: 1,
        plan,
        observation,
        mutated: false,
        source_heads_unchanged: true,
        provider_receipt: None,
        next: "review the exact plan hash, then run `cara native-stack recovery-apply` with the same root/actor/reason and --plan-hash; preview never mutates provider state".to_owned(),
    })
}

/// Apply one independently revalidated recovery plan.
pub fn apply(
    context: &AppContext,
    input: &NativeStackRecoveryApplyInput,
) -> Result<NativeStackRecoveryOutput, AppError> {
    validate_input(input.root, &input.actor, &input.reason)?;
    validate_plan_hash(&input.plan_hash)?;
    let lock = context.acquire_writer_operation("native-stack-recovery")?;
    let deadline = Instant::now() + Duration::from_secs(context.config.sync.max_duration_secs);
    let status = crate::read::fleet_status(context, deadline, None)?;
    crate::initialization::require_ready(&status.initialization)?;
    let root = PrNumber(input.root);
    let pending = crate::stack_membership::load_pending(&context.repository_path, root)?;
    let (plan, observation) = build_plan(
        &context.config,
        &RecoveryFacts::from_status(&status),
        root,
        &input.actor,
        &input.reason,
        pending.as_ref(),
    )?;
    if plan.plan_hash != input.plan_hash {
        return Err(refusal(
            "github_stack_recovery_plan_stale",
            "recovery evidence changed after preview; no provider mutation was attempted",
            json!({
                "expected_plan_hash": input.plan_hash,
                "actual_plan_hash": plan.plan_hash,
                "actual_plan": plan,
                "mutated": false,
                "safe_next_action": "review a new recovery-preview receipt; never reuse a stale plan hash",
            }),
        ));
    }

    let timeout = Duration::from_secs(context.config.command_timeout_secs);
    let runner = ProcessRunner::in_directory(&context.repository_path)
        .with_timeout(timeout)
        .with_operation_deadline(deadline);
    let provider = GitHubMutationAdapter::new(lock.runner(runner));
    apply_with_provider(context, plan, observation, &provider)
}

fn apply_with_provider(
    context: &AppContext,
    plan: NativeStackRecoveryPlan,
    observation: NativeStackRecoveryObservation,
    provider: &impl NativeStackRecoveryProvider,
) -> Result<NativeStackRecoveryOutput, AppError> {
    let mut fresh = Vec::with_capacity(plan.members.len());
    for member in &plan.members {
        let pull = provider
            .verify_precondition_with_checks(&plan.repository, &member.expected)
            .map_err(|error| provider_refusal("fresh_member_preflight", &error, &plan))?;
        require_member_green(&pull)?;
        fresh.push(pull);
    }
    let desired = crate::stack_membership::topology_from_members(&plan.desired.base, fresh.iter())
        .map_err(|error| {
            refusal(
                "github_stack_recovery_topology_invalid",
                &error.to_string(),
                json!({"mutated": false, "plan": plan}),
            )
        })?;
    if desired != plan.desired {
        return Err(refusal(
            "github_stack_recovery_generation_changed",
            "fresh member topology differs from the reviewed recovery plan",
            json!({
                "mutated": false,
                "planned": plan.desired,
                "fresh": desired,
                "safe_next_action": "review a new recovery-preview receipt",
            }),
        ));
    }

    let native_receipt = provider
        .converge_membership(&plan.action)
        .map_err(|error| stack_refusal(&error, &plan))?;
    let NativeMembershipReceipt::StackMutation { receipt } = native_receipt else {
        return Err(refusal(
            "github_stack_recovery_action_invalid",
            "multi-member recovery produced a singleton receipt",
            json!({"plan_hash": plan.plan_hash, "mutated": false}),
        ));
    };
    let receipt = *receipt;
    if !receipt.verify() {
        return Err(refusal(
            "github_stack_recovery_receipt_invalid",
            "provider Stack receipt failed its evidence-hash verification",
            json!({
                "mutated": serde_json::Value::Null,
                "mutation_outcome": "indeterminate",
                "provider_receipt": receipt,
                "plan": plan,
                "safe_next_action": "rediscover provider truth before any retry; do not trust an invalid receipt",
            }),
        ));
    }

    // The Stack API must never rewrite source generations. Independently read
    // every PR after the provider receipt and compare the complete mutation
    // identity (head/base/state/labels/auto-merge), excluding only check churn.
    for member in &plan.members {
        provider
            .verify_precondition(&plan.repository, &member.expected)
            .map_err(|error| {
                refusal(
                    "github_stack_recovery_postcondition_changed",
                    "provider Stack converged, but a source PR generation changed during postcondition verification",
                    json!({
                        "plan_hash": plan.plan_hash,
                        "member": member.pr,
                        "provider_receipt": receipt,
                        "source": error.to_string(),
                        "mutated": receipt.disposition != GitHubStackMutationDisposition::AlreadySatisfied,
                        "source_heads_unchanged": false,
                        "safe_next_action": "preserve the Stack receipt and inspect the independently changed PR generation; do not blindly retry recovery",
                    }),
                )
            })?;
    }
    let mutated = receipt.disposition != GitHubStackMutationDisposition::AlreadySatisfied;
    if let Err(error) =
        crate::stack_membership::clear_pending(&context.repository_path, plan.caravan_id)
    {
        return Err(refusal(
            "github_stack_recovery_checkpoint_clear_failed",
            "provider Stack converged, but the local continuation checkpoint could not be cleared",
            json!({
                "plan_hash": plan.plan_hash,
                "provider_receipt": receipt,
                "source": error.to_string(),
                "mutated": mutated,
                "source_heads_unchanged": true,
                "resumable": true,
                "safe_next_action": "preserve the sealed provider receipt; an exact retry is idempotent and may clear the checkpoint",
            }),
        ));
    }
    Ok(NativeStackRecoveryOutput {
        schema_version: 1,
        plan,
        observation,
        mutated,
        source_heads_unchanged: true,
        provider_receipt: Some(receipt),
        next: "run normal `cara status`, then `cara sync --all`; native landing remains fenced by exact Stack mapping, source heads, checks, locks, and topology".to_owned(),
    })
}

fn build_plan(
    config: &CaravanConfig,
    facts: &RecoveryFacts<'_>,
    root: PrNumber,
    actor: &str,
    reason: &str,
    pending: Option<&NativeMembershipCheckpoint>,
) -> Result<(NativeStackRecoveryPlan, NativeStackRecoveryObservation), AppError> {
    require_rollout(config, facts)?;
    let caravan = facts
        .caravans
        .iter()
        .find(|caravan| caravan.id == root)
        .ok_or_else(|| {
            refusal(
                "github_stack_recovery_caravan_missing",
                "the requested exact caravan root is absent",
                json!({"root": root, "mutated": false}),
            )
        })?;
    if caravan.members.len() < 2 {
        return Err(refusal(
            "github_stack_recovery_singleton_forbidden",
            "missing-Stack recovery is only for authoritative multi-member caravans",
            json!({
                "root": root,
                "members": caravan.members,
                "mutated": false,
                "safe_next_action": "use the reviewed singleton landing route; never create a fake one-member provider Stack",
            }),
        ));
    }
    if caravan.parked {
        return Err(refusal(
            "github_stack_recovery_caravan_parked",
            "a parked caravan cannot acquire a native Stack through recovery",
            json!({"root": root, "mutated": false}),
        ));
    }
    if facts
        .pauses
        .iter()
        .any(|pause| pause.record.caravan_head == root && pause.state.is_effective())
    {
        return Err(refusal(
            "github_stack_recovery_caravan_paused",
            "an effective pause blocks native Stack recovery",
            json!({"root": root, "mutated": false}),
        ));
    }

    let (pulls, members) = collect_member_evidence(facts, caravan)?;
    let desired =
        crate::stack_membership::topology_from_members(facts.default_branch, pulls.iter().copied())
            .map_err(|error| {
                refusal(
                    "github_stack_recovery_topology_invalid",
                    &error.to_string(),
                    json!({"root": root, "mutated": false}),
                )
            })?;
    let config_fingerprint = recovery_config_fingerprint(config);
    let topology_hash = crate::membership::fnv1a64(
        &serde_json::to_vec(&desired).expect("native topology serializes"),
    );
    let operation_id = format!("native-stack-recovery-{}-{topology_hash}", root.0);
    let (pending_hash, action) = recovery_action(
        pending,
        facts.repository,
        caravan,
        &desired,
        &pulls,
        &operation_id,
        actor,
    )?;
    let observation = mapping_observation(facts.backend, &caravan.members, &action, &desired)?;
    let plan = NativeStackRecoveryPlan {
        schema_version: 1,
        operation_id,
        repository: facts.repository.clone(),
        caravan_id: root,
        members,
        desired,
        action,
        actor: actor.to_owned(),
        reason: reason.to_owned(),
        config_fingerprint,
        pending_membership_checkpoint_hash: pending_hash,
        mapping_precondition: "zero_create_or_checkpointed_exact_prefix_add_or_exact_desired_retry"
            .to_owned(),
        plan_hash: String::new(),
    }
    .seal();
    Ok((plan, observation))
}

fn collect_member_evidence<'a>(
    facts: &RecoveryFacts<'a>,
    caravan: &Caravan,
) -> Result<(Vec<&'a PullRequestSnapshot>, Vec<NativeStackRecoveryMember>), AppError> {
    let mut pulls: Vec<&PullRequestSnapshot> = Vec::with_capacity(caravan.members.len());
    let mut members = Vec::with_capacity(caravan.members.len());
    for (position, number) in caravan.members.iter().enumerate() {
        let pull = facts.pulls.get(number).ok_or_else(|| {
            refusal(
                "github_stack_recovery_member_missing",
                "one exact caravan member is absent from provider discovery",
                json!({"root": caravan.id, "member": number, "mutated": false}),
            )
        })?;
        require_member_green(pull)?;
        let expected_base = if position == 0 {
            facts.default_branch
        } else {
            &pulls[position - 1].head
        };
        if &pull.base != expected_base {
            return Err(refusal(
                "github_stack_recovery_base_chain_changed",
                "member base does not equal its exact default/predecessor generation",
                json!({
                    "root": caravan.id,
                    "member": number,
                    "observed_base": pull.base,
                    "expected_base": expected_base,
                    "mutated": false,
                }),
            ));
        }
        let (current, superseded) = crate::model::latest_checks_per_identity(&pull.checks);
        members.push(NativeStackRecoveryMember {
            position: u32::try_from(position).map_err(|_| {
                AppError::validation(
                    "github_stack_recovery_too_large",
                    "member position exceeds u32",
                )
            })?,
            pr: *number,
            head_ref: pull.head.name.clone(),
            expected: PullRequestPrecondition::from(pull),
            draft: pull.draft,
            merge_state_status: pull.merge_state_status.clone(),
            authoritative_checks: current.into_iter().cloned().collect(),
            superseded_checks: superseded.into_iter().cloned().collect(),
        });
        pulls.push(pull);
    }
    Ok((pulls, members))
}

fn require_rollout(config: &CaravanConfig, facts: &RecoveryFacts<'_>) -> Result<(), AppError> {
    if !facts.healthy {
        return Err(refusal(
            "github_stack_recovery_status_unhealthy",
            "repository status is unhealthy; provider absence is not mutation authority",
            json!({"mutated": false}),
        ));
    }
    if config.stack_type != StackType::Github
        || !config.stack_rollout.mutations_opt_in
        || config.stack_rollout.reviewed_by.trim().is_empty()
    {
        return Err(refusal(
            "github_stack_recovery_rollout_not_authorized",
            "native Stack recovery requires stack_type github and reviewed mutation opt-in",
            json!({"mutated": false}),
        ));
    }
    if config.physical_branch_rewrites_enabled() {
        return Err(refusal(
            "github_stack_recovery_rebase_on_join_forbidden",
            "native Stack recovery requires immutable source heads with rebase_on_join=false",
            json!({"mutated": false}),
        ));
    }
    if facts.backend.provider_stacks_truncated {
        return Err(refusal(
            "github_stack_recovery_inventory_truncated",
            "truncated provider inventory cannot prove Stack absence or uniqueness",
            json!({"mutated": false}),
        ));
    }
    if facts.backend.capability != StackCapability::Available
        || facts.backend.mutation_support != StackMutationSupport::NativeStack
    {
        return Err(refusal(
            "github_stack_recovery_capability_unavailable",
            "native Stack capability and executable mutation support must both be proven",
            json!({
                "capability": facts.backend.capability,
                "mutation_support": facts.backend.mutation_support,
                "mutated": false,
            }),
        ));
    }
    Ok(())
}

fn require_member_green(pull: &PullRequestSnapshot) -> Result<(), AppError> {
    if pull.state != PullRequestState::Open || pull.draft || pull.merged_at.is_some() {
        return Err(refusal(
            "github_stack_recovery_member_ineligible",
            "every recovery member must be open, non-draft, and unmerged",
            json!({"pr": pull.number, "mutated": false}),
        ));
    }
    if !pull.has_label("caravan") {
        return Err(refusal(
            "github_stack_recovery_membership_missing",
            "every member must retain exact ordinary Cara membership",
            json!({"pr": pull.number, "mutated": false}),
        ));
    }
    if pull.merge_state_status.as_deref() != Some("CLEAN") {
        return Err(refusal(
            "github_stack_recovery_member_not_clean",
            "every member must have exact CLEAN provider mergeability",
            json!({
                "pr": pull.number,
                "merge_state_status": pull.merge_state_status,
                "mutated": false,
            }),
        ));
    }
    let (current, _) = crate::model::latest_checks_per_identity(&pull.checks);
    if current.is_empty()
        || current
            .iter()
            .any(|check| check.state != CheckState::Success)
    {
        return Err(refusal(
            "github_stack_recovery_checks_not_green",
            "every current exact-head check must be successful before recovery",
            json!({"pr": pull.number, "checks": current, "mutated": false}),
        ));
    }
    Ok(())
}

fn recovery_action(
    pending: Option<&NativeMembershipCheckpoint>,
    repository: &RepositoryId,
    caravan: &Caravan,
    desired: &GitHubStackTopology,
    pulls: &[&PullRequestSnapshot],
    operation_id: &str,
    actor: &str,
) -> Result<(Option<String>, NativeMembershipPlan), AppError> {
    let legacy_create = || NativeMembershipPlan::Create {
        plan: Box::new(GitHubStackCreatePlan {
            operation_id: operation_id.to_owned(),
            actor: actor.to_owned(),
            desired: desired.clone(),
        }),
    };
    let Some(pending) = pending else {
        return Ok((None, legacy_create()));
    };
    if !pending.verify() || pending.caravan_id != caravan.id {
        return Err(refusal(
            "github_stack_recovery_checkpoint_invalid",
            "pending native membership checkpoint does not match this caravan",
            json!({"root": caravan.id, "mutated": false}),
        ));
    }
    let action = match &pending.plan {
        NativeMembershipPlan::Create { plan } if &plan.desired == desired => legacy_create(),
        NativeMembershipPlan::Add {
            repository: planned_repository,
            stack_number,
            expected_members,
            candidate,
            ..
        } => {
            let Some(current_candidate) = pulls.last() else {
                return Err(refusal(
                    "github_stack_recovery_checkpoint_drifted",
                    "pending native append has no current candidate",
                    json!({"root": caravan.id, "mutated": false}),
                ));
            };
            let expected_full = expected_members
                .iter()
                .copied()
                .chain(std::iter::once(candidate.number))
                .collect::<Vec<_>>();
            let candidate_matches = PullRequestPrecondition::from(candidate.as_ref())
                .mutation_identity_eq(&PullRequestPrecondition::from(*current_candidate))
                && candidate.head.name == current_candidate.head.name
                && candidate.draft == current_candidate.draft;
            if planned_repository != repository
                || expected_full != caravan.members
                || candidate.number != current_candidate.number
                || !candidate_matches
            {
                return Err(refusal(
                    "github_stack_recovery_checkpoint_drifted",
                    "pending native append does not equal current exact membership topology",
                    json!({
                        "root": caravan.id,
                        "checkpoint": pending,
                        "current_members": caravan.members,
                        "mutated": false,
                    }),
                ));
            }
            NativeMembershipPlan::Add {
                repository: repository.clone(),
                operation_id: operation_id.to_owned(),
                actor: actor.to_owned(),
                stack_number: *stack_number,
                expected_members: expected_members.clone(),
                candidate: Box::new((*current_candidate).clone()),
            }
        }
        _ => {
            return Err(refusal(
                "github_stack_recovery_checkpoint_drifted",
                "pending native membership checkpoint does not equal current exact topology",
                json!({"root": caravan.id, "checkpoint": pending, "mutated": false}),
            ));
        }
    };
    Ok((Some(pending.evidence_hash.clone()), action))
}

fn mapping_observation(
    backend: &StackBackendStatus,
    members: &[PrNumber],
    action: &NativeMembershipPlan,
    desired: &GitHubStackTopology,
) -> Result<NativeStackRecoveryObservation, AppError> {
    let set = members.iter().copied().collect::<BTreeSet<_>>();
    let intersecting = backend
        .native_stacks
        .iter()
        .filter(|native| {
            native
                .stack
                .pull_requests
                .iter()
                .any(|entry| set.contains(&PrNumber(entry.number)))
        })
        .collect::<Vec<_>>();
    let observation = match (action, intersecting.as_slice()) {
        (NativeMembershipPlan::Create { .. }, []) => Some(NativeStackRecoveryObservation::Absent),
        (NativeMembershipPlan::Create { .. }, [native]) if exact_mapping(native, members) => {
            Some(NativeStackRecoveryObservation::ExactAlreadySatisfied)
        }
        (
            NativeMembershipPlan::Add {
                stack_number,
                expected_members,
                ..
            },
            [native],
        ) if exact_prefix_mapping(native, *stack_number, expected_members, desired) => {
            Some(NativeStackRecoveryObservation::ExactPrefixPendingAdd)
        }
        (NativeMembershipPlan::Add { .. }, [native]) if exact_mapping(native, members) => {
            Some(NativeStackRecoveryObservation::ExactAlreadySatisfied)
        }
        _ => None,
    };
    observation.ok_or_else(|| {
        refusal(
            "github_stack_recovery_mapping_ambiguous",
            "provider truth contains missing prerequisite, multiple, partial, or drifted mappings for this recovery action",
            json!({
                "members": members,
                "action": action,
                "mapping_count": intersecting.len(),
                "mappings": intersecting,
                "mutated": false,
            }),
        )
    })
}

fn exact_mapping(native: &NativeStackStatus, members: &[PrNumber]) -> bool {
    native.consistency == crate::read::StackConsistency::Exact
        && native
            .stack
            .pull_requests
            .iter()
            .map(|entry| PrNumber(entry.number))
            .eq(members.iter().copied())
}

fn exact_prefix_mapping(
    native: &NativeStackStatus,
    stack_number: u64,
    expected_members: &[PrNumber],
    desired: &GitHubStackTopology,
) -> bool {
    native.stack.number == stack_number
        && native.stack.base.ref_name == desired.base.name
        && native.stack.pull_requests.len() == expected_members.len()
        && native
            .stack
            .pull_requests
            .iter()
            .zip(desired.entries.iter())
            .zip(expected_members)
            .all(|((observed, expected), number)| {
                PrNumber(observed.number) == *number
                    && expected.pr == *number
                    && observed.state.eq_ignore_ascii_case("open")
                    && !observed.draft
                    && observed.merged_at.is_none()
                    && observed.head.ref_name == expected.head.name
                    && observed.head.sha == expected.head.oid
            })
}

fn recovery_config_fingerprint(config: &CaravanConfig) -> String {
    crate::membership::fnv1a64(
        &serde_json::to_vec(&json!({
            "stack_type": config.stack_type,
            "stack_rollout": config.stack_rollout,
            "rebase_on_join": config.physical_branch_rewrites_enabled(),
        }))
        .expect("recovery config fingerprint serializes"),
    )
}

fn validate_input(root: u64, actor: &str, reason: &str) -> Result<(), AppError> {
    if root == 0 {
        return Err(AppError::validation(
            "github_stack_recovery_root_invalid",
            "recovery root must be a non-zero PR number",
        ));
    }
    for (field, value) in [("actor", actor), ("reason", reason)] {
        let trimmed = value.trim();
        if trimmed.is_empty() || trimmed.len() > MAX_TEXT || trimmed.chars().any(char::is_control) {
            return Err(AppError::validation(
                "github_stack_recovery_text_invalid",
                format!("{field} must be 1..={MAX_TEXT} printable characters"),
            ));
        }
    }
    Ok(())
}

fn validate_plan_hash(plan_hash: &str) -> Result<(), AppError> {
    if plan_hash.len() != 16 || !plan_hash.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(AppError::validation(
            "github_stack_recovery_plan_hash_invalid",
            "plan hash must be the exact 16-character hexadecimal preview hash",
        ));
    }
    Ok(())
}

fn provider_refusal(
    phase: &str,
    error: &MutationError,
    plan: &NativeStackRecoveryPlan,
) -> AppError {
    refusal(
        "github_stack_recovery_generation_changed",
        &format!("{phase} refused exact provider evidence: {error}"),
        json!({
            "phase": phase,
            "plan_hash": plan.plan_hash,
            "source": error.to_string(),
            "mutated": false,
            "safe_next_action": "review a new recovery-preview receipt",
        }),
    )
}

fn stack_refusal(error: &NativeMembershipError, plan: &NativeStackRecoveryPlan) -> AppError {
    let indeterminate = matches!(
        error,
        NativeMembershipError::Stack(
            GitHubStackMutationError::AmbiguousResponse { .. }
                | GitHubStackMutationError::PostconditionFailed { .. }
        )
    );
    refusal(
        "github_stack_recovery_provider_refused",
        &error.to_string(),
        json!({
            "plan_hash": plan.plan_hash,
            "source": error.to_string(),
            "mutated": if indeterminate { serde_json::Value::Null } else { json!(false) },
            "mutation_outcome": if indeterminate { "indeterminate" } else { "none" },
            "resumable": true,
            "safe_next_action": "rediscover provider truth; if no exact receipt exists, review a new recovery-preview before any retry",
        }),
    )
}

fn refusal(code: &str, message: &str, details: serde_json::Value) -> AppError {
    AppError::structured(
        ErrorCategory::Validation,
        code.to_owned(),
        message.to_owned(),
        Some(details),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::StackRolloutConfig;
    use crate::github::{GitHubStackBase, GitHubStackSnapshot};
    use crate::model::{AutoMergeState, CommitOid};
    use crate::read::{StackBackendProblem, StackConsistency};
    use mcp_cli::StructuredError;

    fn repository() -> RepositoryId {
        RepositoryId {
            owner: "acme".to_owned(),
            name: "widgets".to_owned(),
        }
    }

    fn branch(name: &str, oid: &str) -> BranchSnapshot {
        BranchSnapshot {
            repository: repository(),
            name: name.to_owned(),
            oid: CommitOid(oid.to_owned()),
        }
    }

    fn pull(number: u64, base: BranchSnapshot) -> PullRequestSnapshot {
        PullRequestSnapshot {
            number: PrNumber(number),
            title: format!("PR {number}"),
            url: format!("https://example.invalid/{number}"),
            state: PullRequestState::Open,
            draft: false,
            head: branch(&format!("head-{number}"), &format!("{number:040x}")),
            base,
            cross_repository: false,
            labels: BTreeSet::from(["caravan".to_owned()]),
            auto_merge: AutoMergeState::disabled(),
            checks: vec![CheckSnapshot {
                name: "build-test".to_owned(),
                state: CheckState::Success,
                ..CheckSnapshot::default()
            }],
            created_at: None,
            merged_at: None,
            updated_at: None,
            merge_state_status: Some("CLEAN".to_owned()),
        }
    }

    fn config() -> CaravanConfig {
        let mut config = CaravanConfig {
            stack_type: StackType::Github,
            stack_rollout: StackRolloutConfig {
                mutations_opt_in: true,
                reviewed_by: "reviewed-change".to_owned(),
            },
            ..CaravanConfig::default()
        };
        config.rebase_on_join = false;
        config
    }

    fn stack_backend_fixture(native_stacks: Vec<NativeStackStatus>) -> StackBackendStatus {
        StackBackendStatus {
            configured: StackType::Github,
            capability: StackCapability::Available,
            mutation_support: StackMutationSupport::NativeStack,
            native_stacks,
            provider_stacks_truncated: false,
            missing_caravans: vec![PrNumber(101)],
            problems: vec![StackBackendProblem {
                code: "github_stack_absent".to_owned(),
                message: "missing".to_owned(),
            }],
        }
    }

    fn facts<'a>(
        default: &'a BranchSnapshot,
        caravans: &'a [Caravan],
        pulls: &'a BTreeMap<PrNumber, PullRequestSnapshot>,
        backend: &'a StackBackendStatus,
    ) -> RecoveryFacts<'a> {
        RecoveryFacts {
            repository: pulls
                .values()
                .next()
                .map_or(&default.repository, |pull| &pull.head.repository),
            healthy: true,
            default_branch: default,
            caravans,
            pulls,
            backend,
            pauses: &[],
        }
    }

    #[test]
    fn legacy_two_member_zero_mapping_produces_exact_recovery_plan() {
        let main = branch("main", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        let root = pull(101, main.clone());
        let child = pull(102, root.head.clone());
        let caravans = vec![Caravan::new(vec![PrNumber(101), PrNumber(102)]).unwrap()];
        let pulls = BTreeMap::from([(root.number, root.clone()), (child.number, child.clone())]);
        let backend = stack_backend_fixture(Vec::new());

        let (plan, observation) = build_plan(
            &config(),
            &facts(&main, &caravans, &pulls, &backend),
            PrNumber(101),
            "operator",
            "recover exact missing mapping",
            None,
        )
        .expect("exact zero mapping is recoverable");

        assert_eq!(observation, NativeStackRecoveryObservation::Absent);
        assert!(plan.verify());
        assert_eq!(plan.desired.entries.len(), 2);
        assert_eq!(plan.desired.entries[0].head, root.head);
        assert_eq!(plan.desired.entries[1].base, root.head);
        assert_eq!(plan.desired.entries[1].head, child.head);
    }

    #[test]
    fn non_green_or_changed_base_refuses_before_provider_mutation() {
        let main = branch("main", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        let root = pull(101, main.clone());
        let mut child = pull(102, root.head.clone());
        child.checks[0].state = CheckState::Failure;
        let caravans = vec![Caravan::new(vec![PrNumber(101), PrNumber(102)]).unwrap()];
        let pulls = BTreeMap::from([(root.number, root.clone()), (child.number, child.clone())]);
        let backend = stack_backend_fixture(Vec::new());
        assert_eq!(
            build_plan(
                &config(),
                &facts(&main, &caravans, &pulls, &backend),
                PrNumber(101),
                "operator",
                "reason",
                None,
            )
            .unwrap_err()
            .code(),
            "github_stack_recovery_checks_not_green"
        );

        child.checks[0].state = CheckState::Success;
        child.base = main.clone();
        let pulls = BTreeMap::from([(root.number, root), (child.number, child)]);
        assert_eq!(
            build_plan(
                &config(),
                &facts(&main, &caravans, &pulls, &backend),
                PrNumber(101),
                "operator",
                "reason",
                None,
            )
            .unwrap_err()
            .code(),
            "github_stack_recovery_base_chain_changed"
        );
    }

    struct FakeRecoveryProvider {
        pulls: BTreeMap<PrNumber, PullRequestSnapshot>,
        disposition: GitHubStackMutationDisposition,
        creates: std::cell::Cell<u32>,
    }

    impl NativeStackRecoveryProvider for FakeRecoveryProvider {
        fn verify_precondition_with_checks(
            &self,
            _repository: &RepositoryId,
            expected: &PullRequestPrecondition,
        ) -> Result<PullRequestSnapshot, MutationError> {
            self.verify(expected, true)
        }

        fn verify_precondition(
            &self,
            _repository: &RepositoryId,
            expected: &PullRequestPrecondition,
        ) -> Result<PullRequestSnapshot, MutationError> {
            self.verify(expected, false)
        }

        fn converge_membership(
            &self,
            plan: &NativeMembershipPlan,
        ) -> Result<NativeMembershipReceipt, NativeMembershipError> {
            self.creates.set(self.creates.get() + 1);
            let (repository, operation_id, actor, operation, desired) = match plan {
                NativeMembershipPlan::Create { plan } => (
                    plan.desired.base.repository.clone(),
                    plan.operation_id.clone(),
                    plan.actor.clone(),
                    crate::github::GitHubStackMutationOperation::Create,
                    plan.desired.clone(),
                ),
                NativeMembershipPlan::Add {
                    repository,
                    operation_id,
                    actor,
                    expected_members,
                    candidate,
                    ..
                } => {
                    let pulls = expected_members
                        .iter()
                        .map(|number| &self.pulls[number])
                        .chain(std::iter::once(candidate.as_ref()))
                        .collect::<Vec<_>>();
                    let desired = crate::stack_membership::topology_from_members(
                        &pulls[0].base,
                        pulls.iter().copied(),
                    )?;
                    (
                        repository.clone(),
                        operation_id.clone(),
                        actor.clone(),
                        crate::github::GitHubStackMutationOperation::Add,
                        desired,
                    )
                }
                NativeMembershipPlan::AbsentSingleton { .. } => {
                    return Err(NativeMembershipError::InvalidPlan {
                        code: "fixture_singleton".to_owned(),
                        message: "unexpected singleton".to_owned(),
                    });
                }
            };
            let receipt = GitHubStackMutationReceipt {
                schema_version: 1,
                operation_id,
                operation,
                repository: repository.clone(),
                actor,
                disposition: self.disposition,
                request: crate::github::GitHubStackRequestIdentity {
                    method: "POST".to_owned(),
                    path: format!("repos/{}/stacks", repository.slug()),
                    ordered_pull_requests: desired.entries.iter().map(|entry| entry.pr).collect(),
                    github_request_id: Some("request-1".to_owned()),
                },
                before: None,
                after: Some(crate::github::GitHubStackGeneration {
                    id: 1,
                    number: 7,
                    node_id: "S_recovered".to_owned(),
                    open: true,
                    created_at: "2026-08-08T00:00:00Z".to_owned(),
                    topology: desired,
                }),
                provider_output: None,
                evidence_hash: String::new(),
            }
            .seal();
            Ok(NativeMembershipReceipt::StackMutation {
                receipt: Box::new(receipt),
            })
        }
    }

    impl FakeRecoveryProvider {
        fn verify(
            &self,
            expected: &PullRequestPrecondition,
            include_checks: bool,
        ) -> Result<PullRequestSnapshot, MutationError> {
            let actual = self.pulls[&expected.number].clone();
            let actual_precondition = PullRequestPrecondition::from(&actual);
            let identity_matches = expected.mutation_identity_eq(&actual_precondition);
            let checks_match = !include_checks || expected.checks == actual_precondition.checks;
            if identity_matches && checks_match {
                Ok(actual)
            } else {
                Err(MutationError::StalePrecondition {
                    expected: Box::new(expected.clone()),
                    actual: Box::new(actual_precondition),
                    changed_fields: vec!["fixture_generation".to_owned()],
                })
            }
        }
    }

    fn test_context(repository_path: &std::path::Path) -> AppContext {
        let output = std::process::Command::new("git")
            .args(["init", "--quiet"])
            .current_dir(repository_path)
            .output()
            .unwrap();
        assert!(output.status.success());
        AppContext {
            repository_path: repository_path.to_path_buf(),
            config: config(),
            ..AppContext::default()
        }
    }

    #[test]
    fn zero_mapping_recovery_creates_once_and_preserves_source_generations() {
        let directory = tempfile::tempdir().unwrap();
        let context = test_context(directory.path());
        let main = branch("main", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        let root = pull(101, main.clone());
        let child = pull(102, root.head.clone());
        let caravans = vec![Caravan::new(vec![PrNumber(101), PrNumber(102)]).unwrap()];
        let pulls = BTreeMap::from([(root.number, root.clone()), (child.number, child.clone())]);
        let backend = stack_backend_fixture(Vec::new());
        let (plan, observation) = build_plan(
            &context.config,
            &facts(&main, &caravans, &pulls, &backend),
            PrNumber(101),
            "operator",
            "recover exact missing mapping",
            None,
        )
        .unwrap();
        let provider = FakeRecoveryProvider {
            pulls,
            disposition: GitHubStackMutationDisposition::Completed,
            creates: std::cell::Cell::new(0),
        };

        let output = apply_with_provider(&context, plan, observation, &provider).unwrap();

        assert!(output.mutated);
        assert!(output.source_heads_unchanged);
        assert_eq!(provider.creates.get(), 1);
        assert!(output.provider_receipt.unwrap().verify());
        assert_eq!(provider.pulls[&PrNumber(101)].head, root.head);
        assert_eq!(provider.pulls[&PrNumber(102)].head, child.head);
    }

    #[test]
    fn checkpointed_append_recovers_only_from_its_exact_provider_prefix() {
        let directory = tempfile::tempdir().unwrap();
        let context = test_context(directory.path());
        let main = branch("main", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        let root = pull(101, main.clone());
        let child = pull(102, root.head.clone());
        let tail = pull(103, child.head.clone());
        let caravans =
            vec![Caravan::new(vec![PrNumber(101), PrNumber(102), PrNumber(103)]).unwrap()];
        let pulls = BTreeMap::from([
            (root.number, root.clone()),
            (child.number, child.clone()),
            (tail.number, tail.clone()),
        ]);
        let pending_plan = NativeMembershipPlan::Add {
            repository: repository(),
            operation_id: "original-membership".to_owned(),
            actor: "cara".to_owned(),
            stack_number: 7,
            expected_members: vec![PrNumber(101), PrNumber(102)],
            candidate: Box::new(tail),
        };
        let pending = crate::stack_membership::persist_pending(directory.path(), &pending_plan)
            .unwrap()
            .unwrap();
        let native = NativeStackStatus {
            stack: GitHubStackSnapshot {
                id: 7,
                number: 7,
                node_id: "S_prefix".to_owned(),
                base: GitHubStackBase {
                    ref_name: "main".to_owned(),
                },
                open: true,
                created_at: String::new(),
                pull_requests: [&root, &child]
                    .into_iter()
                    .map(|pull| crate::github::GitHubStackPullRequest {
                        number: pull.number.0,
                        state: "OPEN".to_owned(),
                        draft: false,
                        merged_at: None,
                        head: crate::github::GitHubStackPullRequestHead {
                            ref_name: pull.head.name.clone(),
                            sha: pull.head.oid.clone(),
                        },
                    })
                    .collect(),
            },
            caravan_id: Some(PrNumber(101)),
            consistency: StackConsistency::Drifted,
            problems: Vec::new(),
        };
        let backend = stack_backend_fixture(vec![native]);
        let (plan, observation) = build_plan(
            &context.config,
            &facts(&main, &caravans, &pulls, &backend),
            PrNumber(101),
            "operator",
            "resume exact provider append",
            Some(&pending),
        )
        .unwrap();
        assert_eq!(
            observation,
            NativeStackRecoveryObservation::ExactPrefixPendingAdd
        );
        assert!(matches!(&plan.action, NativeMembershipPlan::Add { .. }));
        let provider = FakeRecoveryProvider {
            pulls,
            disposition: GitHubStackMutationDisposition::Completed,
            creates: std::cell::Cell::new(0),
        };

        let output = apply_with_provider(&context, plan, observation, &provider).unwrap();

        assert!(output.mutated);
        assert_eq!(provider.creates.get(), 1);
        assert!(
            crate::stack_membership::load_pending(directory.path(), PrNumber(101))
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn generation_drift_refuses_before_stack_create() {
        let directory = tempfile::tempdir().unwrap();
        let context = test_context(directory.path());
        let main = branch("main", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        let root = pull(101, main.clone());
        let child = pull(102, root.head.clone());
        let caravans = vec![Caravan::new(vec![PrNumber(101), PrNumber(102)]).unwrap()];
        let planned_pulls =
            BTreeMap::from([(root.number, root.clone()), (child.number, child.clone())]);
        let backend = stack_backend_fixture(Vec::new());
        let (plan, observation) = build_plan(
            &context.config,
            &facts(&main, &caravans, &planned_pulls, &backend),
            PrNumber(101),
            "operator",
            "recover exact missing mapping",
            None,
        )
        .unwrap();
        let mut drifted = planned_pulls;
        drifted.get_mut(&PrNumber(102)).unwrap().head.oid =
            CommitOid("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb".to_owned());
        let provider = FakeRecoveryProvider {
            pulls: drifted,
            disposition: GitHubStackMutationDisposition::Completed,
            creates: std::cell::Cell::new(0),
        };

        let error = apply_with_provider(&context, plan, observation, &provider).unwrap_err();

        assert_eq!(error.code(), "github_stack_recovery_generation_changed");
        assert_eq!(provider.creates.get(), 0);
    }

    #[test]
    fn multiple_or_partial_provider_mappings_refuse() {
        let snapshot = |number: u64, members: &[u64]| NativeStackStatus {
            stack: GitHubStackSnapshot {
                id: number,
                number,
                node_id: format!("S_{number}"),
                base: GitHubStackBase {
                    ref_name: "main".to_owned(),
                },
                open: true,
                created_at: String::new(),
                pull_requests: members
                    .iter()
                    .map(|member| crate::github::GitHubStackPullRequest {
                        number: *member,
                        state: "OPEN".to_owned(),
                        draft: false,
                        merged_at: None,
                        head: crate::github::GitHubStackPullRequestHead {
                            ref_name: format!("head-{member}"),
                            sha: CommitOid(format!("{member:040x}")),
                        },
                    })
                    .collect(),
            },
            caravan_id: Some(PrNumber(101)),
            consistency: StackConsistency::Exact,
            problems: Vec::new(),
        };
        let main = branch("main", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        let root = pull(101, main.clone());
        let child = pull(102, root.head.clone());
        let desired =
            crate::stack_membership::topology_from_members(&main, [&root, &child]).unwrap();
        let action = NativeMembershipPlan::Create {
            plan: Box::new(GitHubStackCreatePlan {
                operation_id: "recovery".to_owned(),
                actor: "operator".to_owned(),
                desired: desired.clone(),
            }),
        };
        let backend =
            stack_backend_fixture(vec![snapshot(1, &[101, 102]), snapshot(2, &[101, 102])]);
        assert_eq!(
            mapping_observation(&backend, &[PrNumber(101), PrNumber(102)], &action, &desired,)
                .unwrap_err()
                .code(),
            "github_stack_recovery_mapping_ambiguous"
        );
        let mut partial = snapshot(3, &[101]);
        partial.consistency = StackConsistency::Drifted;
        let backend = stack_backend_fixture(vec![partial]);
        assert_eq!(
            mapping_observation(&backend, &[PrNumber(101), PrNumber(102)], &action, &desired,)
                .unwrap_err()
                .code(),
            "github_stack_recovery_mapping_ambiguous"
        );
    }
}
